project_name: pim
before:
  hooks:
    - go mod tidy
builds:
  - id: pim
    main: .
    binary: pim
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
archives:
  - id: archive
    builds:
      - pim
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  use: git
release:
  github:
    owner: jeircul
    name: pim
