version: "3"

vars:
  BINARY_NAME: pim
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  LDFLAGS: "-s -w -X main.Version={{.VERSION}}"
  INSTALL_DIR: ~/.local/bin

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy dependencies (go.mod/go.sum)
    cmds:
      - go mod tidy

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  build:
    desc: Build for current platform
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY_NAME}} .

  install:
    desc: Install to ~/.local/bin (user-local)
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - go build -ldflags "{{.LDFLAGS}}" -o {{.INSTALL_DIR}}/{{.BINARY_NAME}} .
      - echo "✓ Installed {{.BINARY_NAME}} to {{.INSTALL_DIR}}"

  uninstall:
    desc: Remove from ~/.local/bin
    cmds:
      - rm -f {{.INSTALL_DIR}}/{{.BINARY_NAME}}
      - echo "✓ Removed {{.BINARY_NAME}} from {{.INSTALL_DIR}}"

  clean:
    desc: Clean all build artifacts and coverage files
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf dist/
      - echo "✓ Cleaned build artifacts"

  release:
    desc: Print release instructions
    cmds:
      - |
          echo "1. Ensure git status is clean and up to date"
          echo "2. Set a tag: git tag vX.Y.Z && git push origin vX.Y.Z"
          echo "3. Optionally run task release:snapshot (dry run)"
          echo "4. Run task release:publish to push artefacts (requires GITHUB_TOKEN)"
    silent: true

  release:publish:
    desc: Publish a release to GitHub (requires GITHUB_TOKEN)
    cmds:
      - goreleaser release --clean

  release:snapshot:
    desc: Generate release artefacts locally without publishing
    cmds:
      - goreleaser release --snapshot --clean
